### ISSUE TITLE
current 1.2.4 dev branch fails to start COC

### ISSUE THREAD

**Issue by mathwo** [xbebenk/MBR_xbebenkMod#116]
I rolled back to May 18th commit and it could start Amazon COC. Current latest commit cannot start Amazon nor Google version of COC. LOL

**Comment by NothingJustBlank** [comment]
Amazon version is not supported. 
Check your config, everything is running normally here in our end.

**Comment by mathwo** [comment]
Amazon version was by default in May 18 commit actually if you check the code. Anyway, this is just reporting an issue since rolled back code to May 18 works fine.

**Comment by NothingJustBlank** [comment]
Amazon version is not supported by ANY emulators now. It will not run.
If your bot cannot open the Clash of Clans app, check your config and change the distributor. 
May 18 commit is not made for Amazon by default, and in fact, we never made the Amazon app as our default.
In order to change the game distributor, you will always need to change it in your config.ini
Starting the last major game update, we have only been running the Google Play version of the game. 
If you still cannot run the bot, I suggest to download a fresh version of the Dev Branch and creating a new config.

**Comment by mathwo** [comment]
I see. So it's config.ini in profile folder that controls the distributor. Right now commit on May 18 works fine. Somehow getting latest commit causes some trouble to me. I will stick to that commit.
